services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - internal
    volumes:
      - ./backend/simulate_results.py:/app/simulate_results.py
      - ./backend/simulate_data.py:/app/simulate_data.py

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge